name: cameradroplets

networks:
  cameradroplets_network:
    name: cameradroplets_network
    driver: bridge

services:
  app:
    build: .
    image: cameradroplets:latest
    container_name: cameradroplets
    env_file:
      - .env
    command: ["tail", "-f", "/dev/null"]
    networks:
      - cameradroplets_network

  kafka-broker:
    image: apache/kafka:4.0.2
    container_name: kafka-broker
    hostname: kafka-broker
    ports:
      - "9092:9092"
    env_file:
      - kafka.env
    volumes:
      - ./docker_data/kafka_data:/var/lib/kafka/data
    networks:
      - cameradroplets_network  

  schema-registry:
    image: confluentinc/cp-schema-registry:8.0.1
    container_name: schema-registry
    depends_on:
      - kafka-broker  
    ports:
      - "8081:8081"
    env_file:
      - kafka.env

  schema-registry-init:
    image: curlimages/curl:8.8.0
    container_name: schema-registry-init
    depends_on:
      - schema-registry
    volumes:
      - ./kafka_schemas:/schemas:ro
      - ./scripts/register-schema.sh:/scripts/register-schema.sh:ro
    env_file:
      - kafka.env
    command: ["/bin/sh", "/scripts/register-schema.sh"]
    restart: "no"
    networks:
      - cameradroplets_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    env_file:
      - kafka.env
    depends_on:
      - kafka-broker
      - schema-registry
    networks:
      - cameradroplets_network
